### ISSUE TITLE
AsyncSeq.groupBy?

### ISSUE THREAD

**Issue by eulerfx** [fsprojects/FSharpx.Async#8]
There are use cases for a groupBy operation on AsyncSeq, however the behavior is different from `Seq.groupBy` and perhaps a different name is in order. The use case is as follows - there is an async sequence that represents a stream of data. Each data item is associated with an entity using an identifier. Data items corresponding to the same entity must be processed in order, however data items belonging to different entities can be processed in parallel. Using `AsyncSeq.iterAsync` would process the data items in order, however it does not exploit the parallelism across entities. The groupBy operation would result in a sequence `AsyncSeq<'k * AsyncSeq<'a>>` and it would be iterated by iterating the inner sequences using `iterAsync`. The difference from the usual groupBy is that keys can come and go multiple times in the resulting sequence. This would be to allow processing unbounded sequences. The lifecycle of the sub-sequences can be implemented in a few ways. One would be time based, such that a sub-sequence is alive for a certain time period after which it expires and then when another item with the same key appears, a new pair is returned by the outer sequence. Another would be for the sub-sequences to be expired after each item is processed, unless another item is in progress.

**Comment by polytypic** [comment]
Regarding the design, currently I'm using the following type for `groupBy` with choice streams:

``` fsharp
val groupByJob: ('x -> #Job<'k>) -> Stream<'x> -> Stream<'k * Job<unit> * Stream<'x>> when 'k: equality
```

See the documentation [here](http://hopac.github.io/Hopac/Hopac.html#def:val%20Hopac.Stream.groupByJob).

The idea with this approach is that it enables many different kinds of lifecycle usages.  In particular, one can ignore the close job completely, which means that the substreams are never closed, or one can compose the substream consumer so that it will invoke the close operation at a desired point to close itself (e.g. after a desired number of elements have been processed or after there is a gap of at least a specified timespan between elements in the substream).

This is not to say that I would find this ideal.  Having an explicit close operation feels a bit low level to me.
